### ISSUE TITLE
config.json file is not aligned

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/file-backup#12]
- log file is /var/log/file-backup/log.txt but it should be: /var/log/file-backup/file-backup.log
- mode is set to scoped but it's not used in this way by file upload, do we need the mode or the default one can be used?

**Comment by velitchko-valkov** [comment]
I can look into this :)

**Comment by velitchko-valkov** [comment]
The mode for backup in the configuration file is 'scoped' as the backup directory is meant to serve as a root for other directories. This is unlike the situation in File Upload, where a file filter is used instead.
