### ISSUE TITLE
Specify a default storage location in file-backup.conf

### ISSUE THREAD

**Issue by dimiter-todorov-georgiev** [eclipse-kanto/file-backup#25]
Problem: The storage directory for file-backup is getting created as a sub-directory of whatever the current directory happens to be, which prevents the service from starting on Fedora-IOT, although it works in Debian-based distros.

Suggested solution: Specify a default storage location in /etc/file-backup/config.json. The suggested location is "storage": "/var/lib/file-backup" in /etc/file-backup/config.json, which is resources/config.json in this repository.

**Comment by daniel-milchev** [comment]
I'll have a look at this.
