### ISSUE TITLE
Provide integration tests for the key functionalities

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/file-backup#28]
E2E tests via the component's Ditto API must ensure that controlling the service remotely works.

The key BackupAndRestore Ditto feature and its capabilities and supported use cases must be covered.

**Comment by gboyvalenkov-bosch** [comment]
The tests must cover the key component functionalities and use cases:

- test the backup and restore operations
- verify that the result from the restore operation- the backup files are successfully restored(the contents of backup and restore directories are the same)
- test the _lastUpload_ and _lastOperation_ properties of the _BackupAndRestore_ feature are successfully changed and have the correct values
