### ISSUE TITLE
Eclipse Kanto File Backup initial contribution

### ISSUE THREAD

**Issue by e-grigorov** [eclipse-kanto/file-backup#5]
Currently, there is a file upload that is able to transfer files to a backend storage of choice. This functionality can be extended to transfer files as a part of the backup operation. On restore, the files can be downloaded back to the edge. The related Eclipse Vorto model is: [BackupAndRestore](https://github.com/eclipse/vorto/blob/development/models/com.bosch.iot.suite.manager.backup-BackupAndRestore-1.0.0.fbmodel/model.functionblock)

**Comment by velitchko-valkov** [comment]
I will do this.
